export const LOGIN_AUTH = "LOGIN_AUTH";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAIL = "LOGIN_AUTH_FAIL";

export const REGISTER_AUTH = "REGISTER_AUTH";
export const REGISTER_AUTH_SUCCESS = "REGISTER_AUTH_SUCCESS";
export const REGISTER_AUTH_FAIL = "REGISTER_AUTH_FAIL";

export const LOGOUT_AUTH = "LOGOUT_AUTH";
export const LOGOUT_AUTH_SUCCESS = "LOGOUT_AUTH_SUCCESS";
