export const LOAD_ALL = "LOAD_ALL_BLOG_POSTS";
export const LOAD_ALL_SUCCESS = "LOAD_ALL_SUCCESS_BLOG_POSTS";
export const LOAD_ALL_FAIL = "LOAD_ALL_FAIL_BLOG_POSTS";

export const LOAD_SINGLE = "LOAD_SINGLE_BLOG_POSTS";
export const LOAD_SINGLE_SUCCESS = "LOAD_SINGLE_SUCCESS_BLOG_POSTS";
export const LOAD_SINGLE_FAIL = "LOAD_SINGLE_FAIL_BLOG_POSTS";

export const CREATE = "CREATE_BLOG_POSTS";
export const CREATE_SUCCESS = "CREATE_SUCCESS_BLOG_POSTS";
export const CREATE_FAIL = "CREATE_FAIL_BLOG_POSTS";

export const UPDATE = "UPDATE_BLOG_POSTS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS_BLOG_POSTS";
export const UPDATE_FAIL = "UPDATE_FAIL_BLOG_POSTS";

export const DELETE = "DELETE_BLOG_POSTS";
export const DELETE_SUCCESS = "DELETE_SUCCESS_BLOG_POSTS";
export const DELETE_FAIL = "DELETE_FAIL_BLOG_POSTS";
