export const LOAD_ALL = "LOAD_ALL_BLOG_POSTS_ALL";
export const LOAD_ALL_SUCCESS = "LOAD_ALL_SUCCESS_BLOG_POSTS_ALL";
export const LOAD_ALL_FAIL = "LOAD_ALL_FAIL_BLOG_POSTS_ALL";

export const LOAD_SINGLE = "LOAD_SINGLE_BLOG_POSTS_ALL";
export const LOAD_SINGLE_SUCCESS = "LOAD_SINGLE_SUCCESS_BLOG_POSTS_ALL";
export const LOAD_SINGLE_FAIL = "LOAD_SINGLE_FAIL_BLOG_POSTS_ALL";
